# Generated by Django 3.2 on 2022-02-21 19:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptions', '0002_alter_cat_details_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='adoption_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 19, 24, 24, 570137, tzinfo=utc), verbose_name='date adopted'),
        ),
        migrations.AddField(
            model_name='cat',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
